default:
  image: 'python:3.10-rc'


variables:
  DOCKER_TLS_CERTDIR: ""


stages:
  - lint
  - test
  - build
  - deploy


source_linter:
  stage: lint

  script:
    - cd backend
    - pip3 install -r requirements.txt
    - pip3 install -r requirements.test.txt
    - chmod +x ./run_linter.sh
    - ./run_linter.sh

run_security_checks:
  stage: lint

  script:
    - cd backend
    - pip3 install -r requirements.txt
    - pip3 install -r requirements.test.txt
    - chmod +x ./run_security_check.sh
    - ./run_security_check.sh

measure_coverage:
  stage: test

  script:
    - cd backend
    - pip3 install -r requirements.txt
    - pip3 install -r requirements.test.txt
    - chmod +x ./measure_coverage.sh
    - ./measure_coverage.sh

build_and_push_branch_image:
  stage: build
  image: docker:20.10.6

  services:
    - docker:20.10.6-dind

  only:
    refs:
      - branches

  script:
    - docker login --username=$IMAGE_REGISTRY_CI_USER --password=$IMAGE_REGISTRY_CI_PASSWORD $IMAGE_REGISTRY_URL
    - docker image build -t tradingviewbot .
    - docker image tag tradingviewbot vargab95/tradingviewbot:$CI_COMMIT_BRANCH
    - docker image push vargab95/tradingviewbot:$CI_COMMIT_BRANCH

build_and_push_tag_image:
  stage: build
  image: docker:20.10.6

  services:
    - docker:20.10.6-dind

  only:
    refs:
      - tags

  script:
    - docker login --username=$IMAGE_REGISTRY_CI_USER --password=$IMAGE_REGISTRY_CI_PASSWORD $IMAGE_REGISTRY_URL
    - docker image build -t tradingviewbot .
    - docker image tag tradingviewbot vargab95/tradingviewbot:$CI_COMMIT_TAG
    - docker image push vargab95/tradingviewbot:$CI_COMMIT_TAG
