default:
  image: 'python:3.10-rc'


variables:
  DOCKER_TLS_CERTDIR: ""


stages:
  - testing-build
  - lint
  - test
  - build
  - deploy
  - cleanup


before_script:
  - cd backend


build_and_push_testing_branch_image:
  stage: testing-build
  image: docker:20.10.6

  services:
    - docker:20.10.6-dind

  only:
    refs:
      - branches

  script:
    - docker image build -t tradingviewbot --build-arg include_testing_tools=true .
    - docker image tag tradingviewbot $IMAGE_REGISTRY_CI_USER/tradingviewbot:${CI_COMMIT_SHA}
    - docker image push $IMAGE_REGISTRY_CI_USER/tradingviewbot:${CI_COMMIT_SHA}

source_linter:
  stage: lint
  image: $IMAGE_REGISTRY_CI_USER/tradingviewbot:${CI_COMMIT_SHA}

  script:
    - chmod +x ./run_linter.sh
    - ./run_linter.sh

run_security_checks:
  stage: lint
  image: $IMAGE_REGISTRY_CI_USER/tradingviewbot:${CI_COMMIT_SHA}

  script:
    - chmod +x ./run_security_check.sh
    - ./run_security_check.sh

measure_coverage:
  stage: test
  image: $IMAGE_REGISTRY_CI_USER/tradingviewbot:${CI_COMMIT_SHA}

  script:
    - chmod +x ./measure_coverage.sh
    - ./measure_coverage.sh

build_and_push_branch_image:
  stage: build
  image: docker:20.10.6

  services:
    - docker:20.10.6-dind

  only:
    refs:
      - branches

  script:
    - docker image build -t tradingviewbot .
    - docker image tag tradingviewbot $IMAGE_REGISTRY_CI_USER/tradingviewbot:$CI_COMMIT_BRANCH
    - docker image push $IMAGE_REGISTRY_CI_USER/tradingviewbot:$CI_COMMIT_BRANCH

build_and_push_tag_image:
  stage: build
  image: docker:20.10.6

  services:
    - docker:20.10.6-dind

  only:
    refs:
      - tags

  script:
    - docker image build -t tradingviewbot .
    - docker image tag tradingviewbot $IMAGE_REGISTRY_CI_USER/tradingviewbot:$CI_COMMIT_TAG
    - docker image push $IMAGE_REGISTRY_CI_USER/tradingviewbot:$CI_COMMIT_TAG

delete_testing_image:
  stage: cleanup
  when: always

  image: curlimages/curl

  script:
    - curl -u "$IMAGE_REGISTRY_CI_USER:$IMAGE_REGISTRY_CI_PASSWORD" -X "DELETE" https://cloud.docker.com/v2/repositories/$IMAGE_REGISTRY_CI_USER/tradingviewbot/tags/$CI_COMMIT_SHA/
